### PR TITLE
Fix link to Russian doc and counter

### LINKED ISSUE #69: Поправить ссылку на Яндекс.Счетчик метрики

### PR DESCRIPTION
**Pull request by alexbaumgertner**
replace https://github.com/bem/apw/pull/71

Fix #69 and #70

### CODE REVIEW

**Comment by tadatuta** [comment]
tests fail because of soft deps on `mocha-as-promised`

**Comment by alexbaumgertner** [comment]
@tadatuta 
mocha-as-promised: 
"This Project is Now Deprecated
As of Mocha 1.18.0, Mocha has built-in promise support! Hooray!!"
https://github.com/domenic/mocha-as-promised

(Caution: epileptic image in Readme)

**Comment by alexbaumgertner** [comment]
@tadatuta @arikon build success :)

**Comment by alexbaumgertner** [comment]
@arikon ping

**Comment by arikon** [comment]
@alexbaumgertner Thanks!

**Comment by alexbaumgertner** [comment]
You're welcome!

**Pull request merged**
